<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>

        <div><?php 
/*       $_getMyAttr = $_product->getResource()->getAttribute('offer_text');

// Get Value
echo $attrTestValue = $_getMyAttr->getFrontend()->getValue($_product);


    
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$ruleC=$objectManager->create('Magento\SalesRule\Model\ResourceModel\Coupon\Collection'); 

$current_sku=$_product->getSku(); // Sku you are looking for

//$collection = $objectManager->create('Magento\SalesRule\Model\ResourceModel\Rule\Collection');


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$rulesCollection = $objectManager->create('Magento\SalesRule\Model\ResourceModel\Rule\Collection')->load();

foreach ($rulesCollection as $rule) {
   
        
        $rule = $objectManager->create('Magento\SalesRule\Model\Rule')->load($rule->getId()); 

        $conditions = $rule->getConditions()->asArray();

        foreach( $conditions['conditions'] as $_conditions ):
            foreach( $_conditions['conditions'] as $_condition ):
                $string = explode(',', $_condition['value']);
                for ($i=0; $i<count($string); $i++) {
                    $sku = trim($string[$i]);
                    if ($sku==$current_sku) {
                            $coupans[] =  $rule->getCouponCode(); // Return coupon code that matches the sku condition
                    }
                }
            endforeach;
        endforeach;
    
}*/


//$code_data = $ruleC->getData();



?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
<?php endif; ?>
