<?php $_product = $block->getProduct() ?>
<?php if ($_product->isAvailable()): ?>
<div class="addto-cart-custom-buttons">
    <button type="submit" title="Add to Cart" class="action primary tocart" id="product-addtocart-button-1">
        <span>Add to Cart</span>
    </button>
    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Buy Now') ?>" id="buy-now" class="action buynow primary" data-mage-init='
            {
            "Prince_Buynow/js/buy-now": {
            "form": "#product_addtocart_form"
            }
            }
            '>
        <span><?php /* @escapeNotVerified */ echo __('Buy Now') ?></span>
    </button>
</div>
<?php endif; ?>