<?php

/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $imageBlockBuilder \Magento\Catalog\Block\Product\ImageBlockBuilder
 */
?>
<?php
date_default_timezone_set('Asia/Kolkata');
$currentdate = date('Y-m-d') . " 00:00:00";
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$urldata = $objectManager->create('\Magento\Framework\App\Request\Http');
if ($urldata->getParam('stock') == 1) {
    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
    <?php else: ?>
        <?php echo $block->getToolbarHtml() ?>
        <?php echo $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="products-ajax-main">
            <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                <?php $iterator = 1; ?>
                <ol class="products list items product-items">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php if ($_product->getIsSalable()) { ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item pro-id-' . $_product->getId() . '">' : '</li><li class="item product product-item pro-id-' . $_product->getId() . '">' ?>
                            <div class="product-item-info" data-container="product-grid">
                                <?php
                                $pdtagid = $_product->getProductTag();
                                $attr = $_product->getResource()->getAttribute('product_tag');
                                if ($pdtagid != '') {
                                    if ($attr->usesSource()) {
                                        if ($pdtagid == '96') {
                                            echo $optionText = '<div class="ribbon hot">' . $attr->getSource()->getOptionText($pdtagid) . '</div>';
                                        } else if ($pdtagid == '97') {
                                            echo $optionText = '<div class="ribbon new">' . $attr->getSource()->getOptionText($pdtagid) . '</div>';
                                        } else {
                                            $pid = 'offertextlist' . $_product->getId();
                                            echo $optionText = '<div class="ribbon discount" ><a href="javascript:void(0);"  id="' . $_product->getId() . '">' . $attr->getSource()->getOptionText($pdtagid) . '</a></div>';
                                        }
                                    }
                                }
                                ?>
                                
                                <?php
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                                <?php $parentIds = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable')->getParentIdsByChild($_product->getId());
$parentId = array_shift($parentIds);
if($parentId): 
    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($parentId); 
$color_val = $_product->getData('color');
endif;
?>
                                <?php // Product Image ?>
                                    <?php if($parentId): ?>
                            <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl().'?color='.$color_val; ?>" class="product photo product-item-photo" tabindex="-1"  target="_blank">
                            <?php else: ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1"  target="_blank">
                                <?php endif; ?>
                                    <div class="product-image-wrapper-custom">
                                        <?php echo $productImage->toHtml(); ?>
                                    </div>
                                    <div id="desc_offertextlist<?php echo $_product->getId(); ?>" style="display:none" class="offer_textclass" onmouseout="jQuery(this).hide();">
                                    <!--<div class="offer_closebutton"><a href="javascript:void(0);" onclick="hidebox('desc_offertextlist<?php echo $_product->getId(); ?>')">X</a></div>-->

                                    <?php
                                    $attribute_code = "offer_text"; // attribute with text value
                                    $description_attribute = $_product->getResource()->getAttribute($attribute_code);

//echo  $description_attribute_value = $description_attribute->getFrontend()->getValue($_product);
                                    echo $attribute_value = $_product->getResource()->getAttributeRawValue($_product->getId(), $attribute_code, $_product->getStoreId());
                                    ?>
                                </div> 
                                </a>

                                <div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <?php
                                    if($parentId): 
    ?>
    <strong class="product name product-item-name">
                                    <a class="product-item-link"  target="_blank"
                                       href="<?php /* @escapeNotVerified */ echo $product->getProductUrl().'?color='.$color_val; ?>">
                                           <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
 <?php
 else: ?>
     <strong class="product name product-item-name">
                                    <a class="product-item-link"  target="_blank"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                           <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
<?php endif;
?>
                                
                                
                                <?php 

                                    
                                if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {

 $_children = $_product->getTypeInstance()->getUsedProducts($_product);
  $colorarr = array();
 foreach ($_children as $child){
  $colorarr[$child->getColor()] = $child->getColor();
 }
 $total_shades = count($colorarr);
if($total_shades>1):
echo '<span class="no-of-shades">'.$total_shades.' Shades</span>';
elseif($total_shades==1):
    echo '<span class="no-of-shades">'.$total_shades.' Shade</span>';
endif;
                                }
               ?>
                                    <?php
                                    /* @escapeNotVerified */ echo $block->getProductPrice($_product);
                                    /* echo $_product->getId(); */


                                    /* if ($_product->getDiscount() > 0 && (($_product->getSpecialFromDate() <= $currentdate) && ($_product->getSpecialToDate() >= $currentdate))) {
                                      ?>
                                      <span class="discount"><?php echo "  (-" . intval($_product->getDiscount()) . "%)"; ?></span>
                                      <?php } elseif ($_product->getDiscount() > 0 && ($_product->getSpecialFromDate() == '' && $_product->getSpecialToDate() >= $currentdate)) { ?>

                                      <span class="discount"><?php echo "  (-" . intval($_product->getDiscount()) . "%)"; ?></span>
                                      <?php } elseif ($_product->getDiscount() > 0 && (($_product->getSpecialFromDate() <= $currentdate) && ($_product->getSpecialToDate() == ''))) {
                                      ?>
                                      <span class="discount"><?php echo "  (-" . intval($_product->getDiscount()) . "%)"; ?></span>
                                      <?php } */
                                    $originalPrice = $_product->getPrice();
                                    $finalPrice = $_product->getFinalPrice();

                                    $percentage = 0;
                                    if ($originalPrice > $finalPrice) {
                                        $percentage = number_format(($originalPrice - $finalPrice) * 100 / $originalPrice, 0);
                                    }

                                    if ($percentage) {
                                        echo '<span class="discount">' . $percentage . '%</span>';
                                    }
                                    ?>

                                    <?php echo $block->getProductDetailsHtml($_product);
                                    ?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>


                                    <div class="product-item-inner">
                                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                        <?php echo $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                            <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                    <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        <?php if ($showDescription): ?>
                                            <div class="product description product-item-description">
                                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                                   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <script type="text/javascript">
                                require(['jquery', 'mage/mage', 'Magento_Catalog/product/view/validation',
                                    'Magento_Catalog/js/catalog-add-to-cart'], function ($) {
                                    jQuery(document).ready(function (jQuery) {
                                        var id = <?php echo $_product->getId() ?>;

                                        var discount = jQuery('.products.list li.pro-id-' + id).find('span.discount');
                                        var luckycash = jQuery('.products.list li.pro-id-' + id).find('span.rewards__product-points');

                                        jQuery('.products.list li.pro-id-' + id).find('.price-box.price-final_price').append(discount);
                                        jQuery('.products.list li.pro-id-' + id).find('.price-box.price-final_price').append(luckycash);
                                        jQuery('.products.list li.pro-id-' + id + ' form').catalogAddToCart();
                                    });
                                });
                            </script>
                            <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                        <?php } ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
        <!--  <?php echo $block->getToolbarHtml() ?> -->
        <?php //if (!$block->isRedirectToCartEnabled()) : ?>
        <!--            <script type="text/x-magento-init">
                {
                "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
                }
                }
            </script>-->
        <?php //endif; ?>
    <?php endif; ?>
<?php } else { ?>


    <?php
    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
    <?php else: ?>
        <?php echo $block->getToolbarHtml() ?>
        <?php echo $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="products-ajax-main">
            <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                <?php $iterator = 1; ?>
                <ol class="products list items product-items retretert">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item pro-id-' . $_product->getId() . '">' : '</li><li class="item product product-item pro-id-' . $_product->getId() . '">' ?>
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                            $pdtagid = $_product->getProductTag();
                            $attr = $_product->getResource()->getAttribute('product_tag');
                            if ($pdtagid != '') {
                                if ($attr->usesSource()) {
                                    if ($pdtagid == '96') {
                                        echo $optionText = '<div class="ribbon hot">' . $attr->getSource()->getOptionText($pdtagid) . '</div>';
                                    } else if ($pdtagid == '97') {
                                        echo $optionText = '<div class="ribbon new">' . $attr->getSource()->getOptionText($pdtagid) . '</div>';
                                    } else {
                                        $pid = 'offertextlist' . $_product->getId();
                                        echo $optionText = '<div class="ribbon discount" onmouseover="" id="' . $_product->getId() . '"><a href="javascript:void(0);"  id="' . $_product->getId() . '">' . $attr->getSource()->getOptionText($pdtagid) . '</a></div>';
                                    }
                                }
                            }
                            ?>
                            <?php $parentIds = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable')->getParentIdsByChild($_product->getId());
$parentId = array_shift($parentIds);
if($parentId): 
    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($parentId); 
$color_val = $_product->getData('color');
endif;
?>
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <?php if($parentId): ?>
                            <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl().'?color='.$color_val; ?>" class="product photo product-item-photo" tabindex="-1"  target="_blank">
                            <?php else: ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1"  target="_blank">
                                <?php endif; ?>
                                <div class="product-image-wrapper-custom">
                                    <?php echo $productImage->toHtml(); ?>
                                </div>
                                <div id="desc_offertextlist<?php echo $_product->getId(); ?>" style="display:none" class="offer_textclass" onmouseout="jQuery(this).hide();">
                                <!--<div class="offer_closebutton"><a href="javascript:void(0);" onclick="hidebox('desc_offertextlist<?php echo $_product->getId(); ?>')">X</a></div>-->

                                <?php
                                $attribute_code = "offer_text"; // attribute with text value
                                $description_attribute = $_product->getResource()->getAttribute($attribute_code);

//echo  $description_attribute_value = $description_attribute->getFrontend()->getValue($_product);
                                echo $attribute_value = $_product->getResource()->getAttributeRawValue($_product->getId(), $attribute_code, $_product->getStoreId());
                                ?>
                            </div> 
                            </a>

                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                
                                
if($parentId): 
    ?>
    <strong class="product name product-item-name">
                                    <a class="product-item-link"  target="_blank"
                                       href="<?php /* @escapeNotVerified */ echo $product->getProductUrl().'?color='.$color_val; ?>">
                                           <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
 <?php
 else: ?>
     <strong class="product name product-item-name">
                                    <a class="product-item-link"  target="_blank"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                           <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
<?php endif;
?>
                                
                                
                                <?php 

                                    
                                if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {

 $_children = $_product->getTypeInstance()->getUsedProducts($_product);
  $colorarr = array();
 foreach ($_children as $child){
  $colorarr[$child->getColor()] = $child->getColor();
 }
 $total_shades = count($colorarr);
if($total_shades>1):
echo '<span class="no-of-shades">'.$total_shades.' Shades</span>';
elseif($total_shades==1):
    echo '<span class="no-of-shades">'.$total_shades.' Shade</span>';
endif;
                                }
               ?>
                 <?php
                                /* @escapeNotVerified */ echo $block->getProductPrice($_product);


//                                $product = array();
//                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//
//                                $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());

                                $originalPrice = $_product->getPrice();
                                $finalPrice = $_product->getFinalPrice();
                                $percentage = 0;
                                if ($originalPrice > $finalPrice) {
                                    $percentage = number_format(($originalPrice - $finalPrice) * 100 / $originalPrice, 0);
                                }

                                if ($percentage) {
                                    echo '<span class="discount">(-' . $percentage . '%)</span>';
                                }
                                ?>

                                <?php echo $block->getProductDetailsHtml($_product);
                                ?>
                                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>


                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php if ($showDescription): ?>
                                        <div class="product description product-item-description">
                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                               class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <script type="text/javascript">
                            require(['jquery', 'mage/mage', 'Magento_Catalog/product/view/validation',
                                'Magento_Catalog/js/catalog-add-to-cart'], function ($) {
                                jQuery(document).ready(function (jQuery) {
                                    var id = <?php echo $_product->getId() ?>;

                                    var discount = jQuery('.products.list li.pro-id-' + id).find('span.discount');
                                    var luckycash = jQuery('.products.list li.pro-id-' + id).find('span.rewards__product-points');

                                    jQuery('.products.list li.pro-id-' + id).find('.price-box.price-final_price').append(discount);
                                    jQuery('.products.list li.pro-id-' + id).find('.price-box.price-final_price').append(luckycash);
                                    jQuery('.products.list li.pro-id-' + id + ' form').catalogAddToCart();
                                });
                            });
                        </script>
                        <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
        <!--  <?php echo $block->getToolbarHtml() ?> -->
        <?php //if (!$block->isRedirectToCartEnabled()) : ?>
        <!--            <script type="text/x-magento-init">
                {
                "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
                }
                }
            </script>-->
        <?php //endif; ?>
    <?php endif; ?>

<?php } ?>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        jQuery('body').on('mouseover', '.ribbon.discount a', function () {

            var id = jQuery(this).attr('id');

            jQuery('#desc_offertextlist' + id).show();
        });

        /*jQuery(document).ready(function (jQuery) {
         
         jQuery('body').on('mouseover','.ribbon.discount a',function(){
         
         //jQuery(".ribbon.discount a").hover(function () {
         
         var id = jQuery(this).attr('id');
         
         jQuery('#desc_offertextlist' + id).show();
         }, function () {
         jQuery('#desc_offertextlist' + id).hide();
         });
         });*/
    });

    function hidebox(boxID)
    {
        var box_id = boxID;
        var nid = document.getElementById(box_id);

        nid.style.display = 'none';
    }

</script>

