<?php
	$_helper = $this->helper('Evince\Whatsapp\Helper\Data');
	$buttonSize = $_helper->getButtonSize ();
	$buttonPos = $_helper->getButtonPos();
	$customsharemsg = $_helper->getCustomShareMessage();
	$block->getProduct();
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current category
   $productName = $product->getName();
if(strlen($customsharemsg)>0) {$msg = $customsharemsg; }
else {$msg = "Hey! Take a look at this awesome product:";}
$prd = $productName;
$display_des = $msg.' '.$prd;
?>
<?php 
if($buttonPos == 1 || $buttonPos == 3)
{
?>
<a href="whatsapp://send" data-text='<?php echo $display_des;?>'
	data-href="" class="wa_btn wa_btn_<?php echo $buttonSize?>" style="display:none;">Share</a>
<?php }?>