<?php

/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
date_default_timezone_set('Asia/Kolkata');
$currentdate = date('Y-m-d') . " 00:00:00";
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>
<?php if ($_productCollection->count() > 0): ?>
    <div class="also-viewed-main">
        <h3>Customer Also Viewed</h3>
        <?php echo $block->getToolbarHtml() ?>
        <?php echo $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
            <?php $iterator = 1; ?>
            <div class="products list items product-items also-viewed owl-carousel">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                         <?php $parentIds = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable')->getParentIdsByChild($_product->getId());
$parentId = array_shift($parentIds);
if($parentId): 
    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($parentId); 
$color_val = $_product->getData('color');
endif;
?>
                            <?php // Product Image     ?>
                            <?php if($parentId): ?>
                            <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl().'?color='.$color_val; ?>" class="product photo product-item-photo" tabindex="-1"  target="_blank">
                            <?php else: ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1"  target="_blank">
                                <?php endif; ?>
                            <div class="product-image-wrapper-custom">
                                <?php echo $productImage->toHtml(); ?>
                            </div>
                        </a>

                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <?php
                                    if($parentId): 
    ?>
    <strong class="product name product-item-name">
                                    <a class="product-item-link"  target="_blank"
                                       href="<?php /* @escapeNotVerified */ echo $product->getProductUrl().'?color='.$color_val; ?>">
                                           <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
 <?php
 else: ?>
     <strong class="product name product-item-name">
                                    <a class="product-item-link"  target="_blank"
                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                           <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </strong>
<?php endif;
?>
                                
                                
                                <?php 

                                    
                                if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {

 $_children = $_product->getTypeInstance()->getUsedProducts($_product);
 $colorarr = array();
 foreach ($_children as $child){
  $colorarr[$child->getColor()] = $child->getColor();
 }

 $total_shades = count($colorarr);
if($total_shades>1):
echo '<span class="no-of-shades">'.$total_shades.' Shades</span>';
elseif($total_shades==1):
    echo '<span class="no-of-shades">'.$total_shades.' Shade</span>';
endif;
                                }
               ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                            <?php
                            echo $block->getProductDetailsHtml($_product);
                            $product = array();
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                            $originalPrice = $_product->getPrice();
                            $finalPrice = $_product->getFinalPrice();

                            $percentage = 0;
                            if ($originalPrice > $finalPrice) {
                                $percentage = number_format(($originalPrice - $finalPrice) * 100 / $originalPrice, 0);
                            }

                            if ($percentage) {
                                echo '<span class="discount">(-' . $percentage . '%)</span>';
                            }
                            ?>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?php //echo strpos($pos, $viewMode . '-secondary') ? $position : '';            ?>>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"

                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>'
                                               class="action towishlist" data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <span><?php echo __('Add to Compare') ?></span>
                                        </a>
                                    </div>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php echo($iterator == count($_productCollection) + 1) ? '</div>' : '' ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php echo $block->getToolbarHtml() ?>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
                {
                "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
                }
                }
            </script>
        <?php endif; ?>
    <?php endif; ?>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'owlcarousel'
    ], function ($) {
        $(".also-viewed").owlCarousel({
            margin: 10,
            nav: true,
            dots: false,
            autoplay: true,
            autoplayHoverPause: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                1000: {
                    items: 2
                }
            }
        });
    });
</script>
<script type="text/x-magento-init">
    {
    "*": {
    "Magento_Ui/js/core/app": {
    "components": {
    "wishlist": {
    "component": "Magento_Wishlist/js/view/wishlist"
    }
    }
    }
    }
    }
</script>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery('.products.list .product-item').each(function () {
                var discount = jQuery(this).find('span.discount');
                var luckycash = jQuery(this).find('span.rewards__product-points');
                
                jQuery(this).find('.price-box.price-final_price').append(discount);
                jQuery(this).find('.price-box.price-final_price').append(luckycash);
            });
        });
    });
</script>
