<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<br />
<table class="shipment-track">
    <thead>
        <tr>
            <th><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($_shipment->getAllTracks() as $_item): ?>
        <tr>
            <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
            <?php if($block->escapeHtml($_item->getCarrierCode())=='delhivery'): 
                $url = 'https://ecomexpress.in/tracking/?awb_field='.$block->escapeHtml($_item->getNumber()).'&s='; ?>
            <td><a href="<?php echo $url; ?>" target="_blank"><?= $block->escapeHtml($_item->getNumber()) ?></a></td>
            <?php else: ?>
                <td><?= $block->escapeHtml($_item->getNumber()) ?></td>
            <?php endif; ?> 
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
