<!--<div class="page-loader">

    <div class="custom-load-main">

        <div class="load-image"><img src="<?php //echo $block->getViewFileUrl('images/loading-icon.png'); ?>" alt="loading"/></div>

        <div style="color: #ED2D70" class="la-ball-scale-multiple la-2x">

            <div></div>

            <div></div>

            <div></div>

        </div>

    </div>

</div>-->
<div class="header-top clearfix">    

    <div class="container">        

        <div class="row">

            <div class="col-md-6 col-sm-6 col-xs-6">                

                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-top-left')->toHtml(); ?>            

            </div>            

            <script>

                require([

                    'jquery'

                ], function ($) {

                    jQuery(document).ready(function () {

                        //  jQuery.simpleTicker(jQuery(".offer-ticker"),{'effectType':'roll'});

                        jQuery('.offer-ticker').easyTicker({

                            visible: 1,

                            interval: 4000

                        });

                        jQuery('.offer-ticker').show();

                    });

                });

            </script>    

            <div class="col-md-6 col-sm-6 col-xs-6">                

                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-top-right')->toHtml(); ?>            

            </div>        

        </div>    

    </div>

</div>
<?php


    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseURL=$storeManager->getStore()->getBaseUrl();


?>
<input type="hidden" value="<?php echo $baseURL;?>gift/index/postcode" name="gift_base_url" id="gift_base_url">