<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $this->getBaseUrl();
//$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$loginUrl = $storeManager->getStore()->getUrl('customer/account/login');
$logoutUrl = $storeManager->getStore()->getUrl('customer/account/logout');
$registerUrl = $storeManager->getStore()->getUrl('customer/account/create');
$accountUrl = $storeManager->getStore()->getUrl('customer/account');
$addressBookUrl = $baseUrl . 'customer/address';
$ordersUrl = $baseUrl . 'sales/order/history';
$reviewsUrl = $baseUrl . 'review/customer';
$rewardsUrl = $baseUrl . 'rewards/account';
$referralUrl = $baseUrl . 'rewards/referral';
$blockObj = $block->getLayout()->createBlock('SR\CustomerSession\Block\Customer');
$customer_Id = $blockObj->getCustomerId();
$customerObj = $objectManager->create('Magento\Customer\Model\Customer')
        ->load($customer_Id);
$customerName = $customerObj->getFirstname();
?>
<div class="header-top-login">
    <?php
    if (isset($customer_Id) && $customer_Id != 0) {
        ?>
        <div class="custom-customer-menu-title">
            <span class="customer-wel-title">Hi, <?php echo $customerName; ?></span>
            <i class="fa fa-angle-down" aria-hidden="true"></i>
            <div class="custom-customer-menu-links" style="display: none;">
                <ul>
                    <li><a href="<?php echo $accountUrl; ?>">Account</a></li>
                    <li><a href="<?php echo $addressBookUrl; ?>">Address Book</a></li>
                    <li><a href="<?php echo $ordersUrl; ?>">Orders</a></li>
                    <li><a href="<?php echo $reviewsUrl; ?>">Product Reviews</a></li>
                    <li><a href="<?php echo $this->getUrl('wishlist'); ?>">Wish List</a></li>
<!--                    <li><a href="<?php //echo $rewardsUrl; ?>">Reward Points</a></li>-->
                    <li><a href="<?php echo $referralUrl; ?>">Referrals</a></li>
                    <li><a href="<?php echo $logoutUrl; ?>">Sign Out</a></li>
                </ul>
            </div>
        </div>
        <?php
    } else {
        ?>
        <div class="custom-customer-menu-title">
            <span class="customer-wel-title">Hi! Beautiful</span>
            <i class="fa fa-angle-down" aria-hidden="true"></i>
            <div class="custom-customer-menu-links" style="display: none;">
                <ul>
                    <?php
                    $url = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
                    $login_url = $block->getUrl('customer/account/login', array('referer' => base64_encode($url)));
                    ?>
                    <li><a href="<?php echo $login_url; ?>">Sign In</a></li>
                    <li><a href="<?php echo $registerUrl; ?>">Register</a></li>
                </ul>
            </div>
        </div>
        <?php
    }
    ?>
</div>