<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
date_default_timezone_set('Asia/Kolkata');
$currentdate = date('Y-m-d') . " 00:00:00";
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist): ?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
            <?php else: ?>
                <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
                <?php endif; ?>
            <?php else: ?>
                <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
                <?php endif; ?>
                <!--                <div class="block-title title">
                                    <strong id="block-<?php /* @escapeNotVerified */ //echo $class        ?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ //echo $title;        ?></strong>
                                </div>-->
                <div class="block-title-main">
                    <h2><?php /* @escapeNotVerified */ echo $title; ?></h2>
                    <div class="title-border"></div>
                </div>
                <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class ?>-heading">
                    <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                        <div class="products list items product-items owl-carousel">
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?php $available = ''; ?>
                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <?php $available = 'related-available'; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if ($type == 'related' || $type == 'upsell'): ?>
                                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item" style="display: none;">' : '</div><div class="item product product-item" style="display: none;">' ?>
                                <?php else: ?>
                                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                                <?php endif; ?>
                                <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                                    <?php
                                    $parentIds = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable')->getParentIdsByChild($_item->getId());
                                    $parentId = array_shift($parentIds);
                                    if ($parentId):
                                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($parentId);
                                        $color_val = $_item->getData('color');
                                    endif;
                                    ?>
                                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                    <?php if ($parentId): ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() . '?color=' . $color_val; ?>" class="product photo product-item-photo" tabindex="-1"  target="_blank">
                                        <?php else: ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo" tabindex="-1"  target="_blank">
                                            <?php endif; ?>
                                            <div class="product-image-wrapper-custom">
                                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                            </div>
                                        </a>

                                        <div class="product details product-item-details">
                                            
                                            <?php
                                            if ($parentId):
                                                ?>
                                            <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() . '?color=' . $color_val; ?>">
                                                    <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                            </strong>
                                            <?php else:
                                                ?>
                                                <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                    <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                            </strong>
                                            <?php endif;
                                            ?>


                                            <?php
                                            if ($_item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {

                                                $_children = $_item->getTypeInstance()->getUsedProducts($_item);
                                                $colorarr = array();
                                                foreach ($_children as $child) {
                                                    $colorarr[$child->getColor()] = $child->getColor();
                                                }

                                                $total_shades = count($colorarr);
                                                if ($total_shades > 1):
                                                    echo '<span class="no-of-shades">' . $total_shades . ' Shades</span>';
                                                elseif ($total_shades == 1):
                                                    echo '<span class="no-of-shades">' . $total_shades . ' Shade</span>';
                                                endif;
                                            }
                                            ?>

                                            <?php
                                            /* @escapeNotVerified */ echo $block->getProductPrice($_item);
                                            $product = array();
                                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                            $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
                                            if ($product->getDiscount() > 0 && (($product->getSpecialFromDate() <= $currentdate) && ($product->getSpecialToDate() >= $currentdate))) {
                                                ?>
                                                <span class="discount"><?php echo "  (-" . intval($product->getDiscount()) . "%)"; ?></span>
                                            <?php } elseif ($product->getDiscount() > 0 && ($product->getSpecialFromDate() == '' && $product->getSpecialToDate() >= $currentdate)) { ?>

                                                <span class="discount"><?php echo "  (-" . intval($product->getDiscount()) . "%)"; ?></span>
                                            <?php } elseif ($product->getDiscount() > 0 && (($product->getSpecialFromDate() <= $currentdate) && ($product->getSpecialToDate() == ''))) {
                                                ?>
                                                <span class="discount"><?php echo "  (-" . intval($product->getDiscount()) . "%)"; ?></span>
                                            <?php } ?>



                                            <?php if ($templateType): ?>
                                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                            <?php endif; ?>



                                            <?php if ($showAddTo || $showCart): ?>

                                                <div class="product actions product-item-actions">
                                                    <?php if ($showCart): ?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                <?php else: ?>
                                                                    <?php
                                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                    ?>
                                                                    <button class="action tocart primary"
                                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            <?php else: ?>
                                                                <?php if ($_item->getIsSalable()): ?>
                                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                                <?php else: ?>
                                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>

                                                    <?php if ($showAddTo): ?>
                                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                                <?php echo $addToBlock->setProduct($_item)->getChildHtml(); ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>

                                            <?php endif; ?>
                                        </div>
                                </div>
                                <?php echo($iterator == count($items) + 1) ? '</div>' : '' ?>
                            <?php endforeach ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <script type="text/javascript">
            require([
                'jquery',
                'owlcarousel'
            ], function ()
            {
                jQuery(document).ready(function () {
                    jQuery(".products-related .owl-carousel").owlCarousel({
                        margin: 10,
                        nav: true,
                        autoplay: true,
                        autoplayHoverPause: true,
                        dots: false,
                        responsive: {
                            0: {
                                items: 1
                            },
                            600: {
                                items: 3
                            },
                            1000: {
                                items: 4
                            }
                        }
                    });
                    jQuery(".products-crosssell .owl-carousel").owlCarousel({
                        margin: 10,
                        nav: true,
                        dots: false,
                        autoplay: true,
                        autoplayHoverPause: true,
                        responsive: {
                            0: {
                                items: 1
                            },
                            600: {
                                items: 3
                            },
                            1000: {
                                items: 4
                            }
                        }
                    });
                    jQuery('.products-crosssell .product-item').each(function () {
                        var discount = jQuery(this).find('span.discount');
                        var luckycash = jQuery(this).find('span.rewards__product-points');

                        jQuery(this).find('.price-box.price-final_price').append(discount);
                        jQuery(this).find('.price-box.price-final_price').append(luckycash);
                    });
                    jQuery('.products-related .product-item').each(function () {
                        var discount = jQuery(this).find('span.discount');
                        var luckycash = jQuery(this).find('span.rewards__product-points');

                        jQuery(this).find('.price-box.price-final_price').append(discount);
                        jQuery(this).find('.price-box.price-final_price').append(luckycash);
                    });
                });
            });
        </script>
