<?php $categories = $block->getCategoryList(); ?>
<div class="products wrapper grid products-grid subcategories-listing">
<ol class="products list items product-items">
        <?php foreach ($categories as $category): ?>
            <li class="item product product-item" style="width:13%">
                <div class="product-item-info">
                        
                    <?php if ($category['thumbnail_image']): ?>
                        <a class="subcat_img" href="<?php echo $category->getUrl() ?>" target="_blank" title="<?php echo $category->getName() ?>">

                        <img src="<?php echo $block->getCategoryThumbImage($category['thumbnail_image']); ?>"  />

                        </a>
                    <?php else: ?>
                        <a class="subcat_img" href="<?php echo $category->getUrl() ?>"  target="_blank"  title="<?php echo $category->getName() ?>"><img src="<?php echo $block->getViewFileUrl($block->getPlaceholderImage()); ?>" /></a>
                    <?php endif; ?>
                    

                    <div class="product details product-item-details">
                        <strong class="product name product-item-name category-item-name">
                            <a href="<?php echo $category->getUrl() ?>"  target="_blank"  title="<?php echo $category->getName() ?>"><?php echo $category->getName() ?></a>
                        </strong>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
    </div>